### ISSUE TITLE
[replay] Validation errors when replaying RayTracingInVulkan

### ISSUE THREAD

**Issue by nhaehnle** [LunarG/gfxreconstruct#1381] opened 2023-12-03 12:26 UTC
**Describe the replay bug:**

Replay of RayTracingInVulkan shows validation errors that weren't there during recording:
```
VUID-vkBindBufferMemory-bufferDeviceAddress-03339(ERROR / SPEC): msgNum: 1151829889 - Validation Error: [ VUID-vkBindBufferMemory-bufferDeviceAddress-03339 ] Object 0: handle = 0xc4f3070000000021, type = VK_OBJECT_TYPE_BUFFER; Object 1: handle = 0x301e6c0000000022, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0x44a78781 | vkBindBufferMemory(): buffer was created with the VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT bit set, memory must have been allocated with the VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT bit set. The Vulkan spec states: If the VkPhysicalDeviceBufferDeviceAddressFeatures::bufferDeviceAddress feature is enabled and buffer was created with the VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT bit set, memory must have been allocated with the VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT bit set (https://vulkan.lunarg.com/doc/view/1.3.268.0/linux/1.3-extensions/vkspec.html#VUID-vkBindBufferMemory-bufferDeviceAddress-03339)
```

**Verify before submission:**
* Was trimming enabled? --> *No*
* Was replayer renamed if necessary? --> *No*
* Was --sync used if title is known to need forced synchronization? --> *No*

**Build Environment:**
Current dev, commit `548080b88a6efbdc93eee19d5d9d5bb3d4009e53`

**To Reproduce**
1. Record using `gfxrecon-capture-vulkan.py` with no parameters other than `--capture-layer`
2. Or get the `.gfxr` file from [capture.zip](https://github.com/LunarG/gfxreconstruct/files/13538876/capture.zip)
3. Run gfxrecon-replay with no parameters (I enable validation using `vkconfig`, presumably you could also use `--validate`)

**Screenshots:**
(n/a)

**System environment:**
- Radeon RX 7900 XTX with AMDVLK/XGL driver on Ubuntu 23.10

**Title configuration:**
RayTracingInVulkan, commit `164e530154cc4af465167ed88e743684424eaec6`

**Comment by bradgrantham-lunarg** [comment] 2023-12-04 23:50
Hi, @nhaehnle !  Thanks for your issue.  I'm not able to build RayTracingInVulkan on my Windows machine at this time (it looks like `vcpkg_windows.bat` references packages that are no longer mirrored on servers.  If I can find time, I'll try to build it and run it.   

Can you try running the replay with `-m rebind`?

**Comment by bradgrantham-lunarg** [comment] 2023-12-05 00:09
Investigation notes:
* When we capture on a system with `bufferAddressCaptureReplay`, e.g. for ray-tracing acceleration structure buffer addresses, if the buffer is created with `VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR` we add `VK_BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT `so we can get the same GPU address in replay.
* binding a VkMemory without `VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT `to a `VkBuffer `with `VK_BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT `precipitates a `VUID-vkBindBufferMemory-bufferDeviceAddress-03339` message
* Because we do not know `VkBuffer `and `VkImage` binding until `VkBindBufferMemory `time, we cannot add `VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT `to the `VkMemory `creation.

We may need to rely on `-m rebind` to set the correct bits on the `VkMemory` to match the requirements of the `VkBuffer`.

* Also, adding `VK_BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT` is only valid usage if the `VkBuffer` is created with `VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT`; best I can tall at the moment reading `src/Vulkan/RayTracing/Application.cpp`, in this case the buffer was *not* created with `SHADER_DEVICE_ADDRESS_BIT`, so do we need to investigate whether we are incorrectly setting that bit?  Or is RayTracingInVulkan doing something incorrect that VVL isn't catching?

**Comment by bradgrantham-lunarg** [comment] 2023-12-06 00:31
I was able to build RayTracingInVulkan from Visual Studio 2022 Developer Command Prompt using `vcpkg_windows.bat` and then `build_windows.bat` with this patch applied and then verify invalid usage in `replay` of a capture.
```
diff --git a/src/ImGui/imgui_impl_vulkan.cpp b/src/ImGui/imgui_impl_vulkan.cpp
index dbd8b18..094e515 100644
--- a/src/ImGui/imgui_impl_vulkan.cpp
+++ b/src/ImGui/imgui_impl_vulkan.cpp
@@ -823,15 +823,15 @@ static void ImGui_ImplVulkan_CreatePipeline(VkDevice device, const VkAllocationC
     attribute_desc[0].location = 0;
     attribute_desc[0].binding = binding_desc[0].binding;
     attribute_desc[0].format = VK_FORMAT_R32G32_SFLOAT;
-    attribute_desc[0].offset = IM_OFFSETOF(ImDrawVert, pos);
+    attribute_desc[0].offset = offsetof(ImDrawVert, pos);
     attribute_desc[1].location = 1;
     attribute_desc[1].binding = binding_desc[0].binding;
     attribute_desc[1].format = VK_FORMAT_R32G32_SFLOAT;
-    attribute_desc[1].offset = IM_OFFSETOF(ImDrawVert, uv);
+    attribute_desc[1].offset = offsetof(ImDrawVert, uv);
     attribute_desc[2].location = 2;
     attribute_desc[2].binding = binding_desc[0].binding;
     attribute_desc[2].format = VK_FORMAT_R8G8B8A8_UNORM;
-    attribute_desc[2].offset = IM_OFFSETOF(ImDrawVert, col);
+    attribute_desc[2].offset = offsetof(ImDrawVert, col);

     VkPipelineVertexInputStateCreateInfo vertex_info = {};
     vertex_info.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
diff --git a/vcpkg_windows.bat b/vcpkg_windows.bat
index fce8041..e6e1e82 100644
--- a/vcpkg_windows.bat
+++ b/vcpkg_windows.bat
@@ -2,7 +2,8 @@ mkdir build
 cd build || goto :error
 git clone https://github.com/Microsoft/vcpkg.git vcpkg.windows || goto :error
 cd vcpkg.windows || goto :error
-git checkout 2023.04.15 || goto :error
+rem git checkout 2023.04.15
+git checkout 2023.11.20 || goto :error
 call bootstrap-vcpkg.bat || goto :error

 vcpkg.exe install ^

```

**Comment by nhaehnle** [comment] 2023-12-12 20:02
Hi Brad, thank you for investigating!

FWIW, when I add `-m rebind` to the options during replay, I get a ton of validation errors like the following, followed by a GPU fault:
```
VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03802(ERROR / SPEC): msgNum: 787975915 - Validation Error: [ VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03802 ] | MessageID = 0x2ef78eeb | vkCmdBuildAccelerationStructuresKHR(): No buffer is associated with pInfos[0].scratchData.deviceAddress (0x7ffc0119b200). The Vulkan spec states: For each element of pInfos, its scratchData.deviceAddress member must be a valid device address obtained from vkGetBufferDeviceAddress (https://vulkan.lunarg.com/doc/view/1.3.261.0/linux/1.3-extensions/vkspec.html#VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03802)
```
On your investigation notes: Is there a reason not to use `VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT` unconditionally?

**Comment by fabian-lunarg** [comment] 2024-04-08 10:15
hello @nhaehnle! 

- I was able to reproduce your reported ```VUID-vkBindBufferMemory-bufferDeviceAddress-03339``` during a replay using ```gfxrecon-replay --validate foo.gfxr```. 
- running the original "Raytracer" application with validation-layers enabled I'm seeing:
 `The buffer on which pInfo->accelerationStructure was placed must have been created with the VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT usage flag (https://vulkan.lunarg.com/doc/view/1.3.280.0/linux/1.3-extensions/vkspec.html#VUID-vkGetAccelerationStructureDeviceAddressKHR-pInfo-09542) `
- I'm unable to reproduce reported ```VUID-vkBindBufferMemory-bufferDeviceAddress-03339``` with replays of captures of other applications using VK_KHR_raytracing / VK_KHR_application.

to me it looks the reported validation-warning in your capture-replay, while not identical, is a consequence of improper API-usage in the original application (buffer missing `VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT`).

**Comment by fabian-lunarg** [comment] 2024-04-08 10:25
I'm closing this issue, but created a follow-up in 'RaytracingInVulkan'-repo, in case you want to track it:

https://github.com/GPSnoopy/RayTracingInVulkan/issues/78

**Closed by fabian-lunarg** 2024-04-08 10:25 UTC
Labels: P1, replay

**Comment by nhaehnle** [comment] 2024-04-16 16:55
Thanks for digging into it!
