### ISSUE TITLE
Output return values of certain functions as hexadecimals instead of decimals

### ISSUE THREAD

**Issue by panos-lunarg** [LunarG/gfxreconstruct#912] opened 2022-11-29 10:26 UTC
I can think of two functions that return a pointer
`vkGetAccelerationStructureDeviceAddressKHR` and `vkGetBufferDeviceAddress[EXT|KHR]`
In the output file those values are output as decimals. For example:
```
{
    "index": 5232,
    "vkFunc": {
        "name": "vkGetBufferDeviceAddress",
        "return": "13161725952",
        ...
```
but the return value can be used in other vulkan functions and in there the value is printed as hexadecimal. For example:
```
    "vkFunc": {
        "name": "vkGetAccelerationStructureBuildSizesKHR",
        "args": {
...
                                "vertexData": {
                                    "deviceAddress": "0x310800740",
                                    "hostAddress": "0x310800740"
                                },
                                "vertexStride": 8,
                                "maxVertex": 3750,
                                "indexType": "VK_INDEX_TYPE_UINT16",
                                "indexData": {
                                    "deviceAddress": "0x312000570",
                                    "hostAddress": "0x312000570"
                                },

```

It would be convenient if the output of the `vklGet...DeviceAddress` would be in hex as well.

**Comment by andrew-lunarg** [comment] 2022-11-29 11:51
Good catch!

Looking into this a little, the problem is that the return type, while an address, is just a typedefed integer: ` typedef uint64_t VkDeviceAddress;`. So the use of function overloading and C++ name resolution to find an appropriate `ToString` function fails, falling back to the generic template version at the top of `framework/util/to_string.h`.

A list of all current non-`VkResult` returns from generated functions (there may be others whose string output is handled by custom manual code):
```
Return type:  VkDeviceAddress  from function:  vkGetBufferDeviceAddress
Return type:  uint64_t  from function:  vkGetBufferOpaqueCaptureAddress
Return type:  uint64_t  from function:  vkGetDeviceMemoryOpaqueCaptureAddress
Return type:  VkBool32  from function:  vkGetPhysicalDeviceXlibPresentationSupportKHR
Return type:  VkBool32  from function:  vkGetPhysicalDeviceXcbPresentationSupportKHR
Return type:  VkBool32  from function:  vkGetPhysicalDeviceWaylandPresentationSupportKHR
Return type:  VkBool32  from function:  vkGetPhysicalDeviceWin32PresentationSupportKHR
Return type:  VkDeviceAddress  from function:  vkGetBufferDeviceAddressKHR
Return type:  uint64_t  from function:  vkGetBufferOpaqueCaptureAddressKHR
Return type:  uint64_t  from function:  vkGetDeviceMemoryOpaqueCaptureAddressKHR
Return type:  uint32_t  from function:  vkGetDeferredOperationMaxConcurrencyKHR
Return type:  uint32_t  from function:  vkGetImageViewHandleNVX
Return type:  VkDeviceAddress  from function:  vkGetBufferDeviceAddressEXT
Return type:  VkBool32  from function:  vkGetPhysicalDeviceDirectFBPresentationSupportEXT
Return type:  VkBool32  from function:  vkGetPhysicalDeviceScreenPresentationSupportQNX
Return type:  VkDeviceAddress  from function:  vkGetAccelerationStructureDeviceAddressKHR
Return type:  VkDeviceSize  from function:  vkGetRayTracingShaderGroupStackSizeKHR
```

Both the Bool32 and VkDeviceAddress examples need fixing, but that should be clean and straightforward in `framework/generated/vulkan_generators/vulkan_ascii_consumer_body_generator.py`. Examples like `vkGetBufferOpaqueCaptureAddress` which don't bother to use the VkDeviceAddress typedef will need to be listed in that generator and checked-for by it).

I'd note that the "good" examples in the description contain another issue that is already tracked: multiple options of a union being output rather than just the one that makes sense in the current context:
```
"vertexData": {
                                    "deviceAddress": "0x310800740",
                                    "hostAddress": "0x310800740" // In C this occupies same location as above
                                }
```

**Comment by andrew-lunarg** [comment] 2023-01-05 21:19
This was fixed by https://github.com/LunarG/gfxreconstruct/pull/913

**Closed by andrew-lunarg** 2023-01-05 21:19 UTC
Labels: P2, convert
