### ISSUE TITLE
[capture] Opaque capture address misuse

### ISSUE THREAD

**Issue by dorian-apanel-intel** [LunarG/gfxreconstruct#1623] opened 2024-07-11 21:14 UTC
I've encountered an assertion failure while attempting to capture an application that utilizes acceleration structures.

It appears that gfx-reconstruct is relying on the opaque capture address obtained from vkGetDeviceMemoryOpaqueCaptureAddress to infer the corresponding vkDeviceMemory for a given address retrieved from vkGetAccelerationStructureDeviceAddress.

From my understanding of the specification, there is no assurance that this method will be successful. Opaque addresses should not be compared or offset against one another. A buffer's opaque capture address can be completely different from its BufferDeviceAddress. Furthermore, even if a buffer is bound to a particular memory at offset 0, the buffer and the memory may have distinct opaque capture addresses.

Code triggering assert:
```
void VulkanStateTracker::TrackTlasToBlasDependencies(uint32_t               command_buffer_count,
                                                     const VkCommandBuffer* command_buffers)
{
    ...
    for (uint32_t c = 0; c < command_buffer_count; ++c)
    {
        const vulkan_wrappers::CommandBufferWrapper* cmd_buf_wrapper =
            GetVulkanWrapper<vulkan_wrappers::CommandBufferWrapper>(command_buffers[c]);

        for (const auto& tlas_build_info : cmd_buf_wrapper->tlas_build_info_map)
        {
            // Sanity checks. Build infos with one of these 0 should not be inserted in the map
            assert(tlas_build_info.second.address);
            assert(tlas_build_info.second.blas_count);

            // Find to which device memory this address belongs
            const VkDeviceAddress                       address         = tlas_build_info.second.address;
            const vulkan_wrappers::DeviceMemoryWrapper* dev_mem_wrapper = nullptr;
            for (const auto& dev_mem : device_memory_addresses_map)
            {
                if (address >= dev_mem.second->address &&
                    address < dev_mem.second->address + dev_mem.second->allocation_size)
                {
                    dev_mem_wrapper = dev_mem.second;
                    break;
                }
            }

            assert(dev_mem_wrapper);
```

Stack trace:
```
VkLayer_gfxreconstruct.dll!gfxrecon::encode::VulkanStateTracker::TrackTlasToBlasDependencies(unsigned int command_buffer_count, VkCommandBuffer_T * const * command_buffers) Line 1582	C++
VkLayer_gfxreconstruct.dll!gfxrecon::encode::VulkanCaptureManager::PreProcess_vkQueueSubmit(VkQueue_T * queue, unsigned int submitCount, const VkSubmitInfo * pSubmits, VkFence_T * fence) Line 2414	C++
VkLayer_gfxreconstruct.dll!gfxrecon::encode::CustomEncoderPreCall<69650>::Dispatch<VkQueue_T *,unsigned int,VkSubmitInfo const *,VkFence_T *>(gfxrecon::encode::VulkanCaptureManager * manager, VkQueue_T * <args_0>, unsigned int <args_1>, const VkSubmitInfo * <args_2>, VkFence_T * <args_3>) Line 680	C++
VkLayer_gfxreconstruct.dll!gfxrecon::encode::QueueSubmit(VkQueue_T * queue, unsigned int submitCount, const VkSubmitInfo * pSubmits, VkFence_T * fence) Line 537	C++
```

**Build Environment:**
commit 1a174b86cc85df6c9e2744c3877345ab46ac87ef (HEAD, tag: vulkan-sdk-1.3.283.0, origin/vulkan-sdk-1.3.283)

**Capture Settings:**
Standard settings from vkconfig with specific frames to capture eg 80-90.

**System environment:**
Intel GFX under Windows, internal test driver

**Title configuration:**
Not allowed to share.

**Comment by fabian-lunarg** [comment] 2024-08-12 15:46
yes, can confirm we currently have still have shortcomings wrt. raytracing & accelration-structures on vulkan:
 
https://github.com/LunarG/gfxreconstruct/issues/1526

**Comment by fabian-lunarg** [comment] 2024-08-12 15:49
closing as duplicate of https://github.com/LunarG/gfxreconstruct/issues/1526,
thanks for your report @dorian-apanel-intel

**Closed by fabian-lunarg** 2024-08-12 15:49 UTC
