### ISSUE TITLE
Android 12, Pixel 6 gets locked in AcquireUniqueStateLock()

### ISSUE THREAD

**Issue by locke-lunarg** [LunarG/gfxreconstruct#716] opened 2022-06-08 23:44 UTC
When I tried capturing vkcube for Android 12, Pixel 6, it was locked in AcquireUniqueStateLock() of CaptureManager::CreateCaptureFile. It didn't happen always, but very high chance. It didn't happen in Android 10 and 11, Pixel 3. It could be fixed temporarily by removing AcquireUniqueStateLock().
https://github.com/LunarG/gfxreconstruct/blob/dev/framework/encode/capture_manager.cpp#L618

**Comment by panos-lunarg** [comment] 2022-06-24 10:53
I installed the AOSP version of Android 12 on my Pixel 3.
So far I wasn't able to reproduce the hang. I also tried with something like
`setprop debug.gfxrecon.capture_frames "1-4,10-14,20-25,30-35,50-55,60-65,70-75,80-85,90-95,100-105,110-115,120-125,130-135,140-145" `
in order to call `AcquireUniqueStateLock()` multiple times per run but still no luck.

**Comment by locke-lunarg** [comment] 2022-06-24 16:15
I think it requires Pixel 6. I figured out some mechanisms happened in Pixel 6, but not Pixel 3, even both were Android 12. Maybe it's GPU reason or something else. Pixel 6 GPU is Mali. Pixel 3 GPU is Adreno. For example, it captured twice vkCreateInstance and vkCreateDevice that application info is `android framework` in Pixel 6. But it didn't happen in Pixel 3 Android 12.

**Comment by panos-lunarg** [comment] 2022-07-05 12:54
Indeed it is very easy to reproduce on Pixel 6 with Android 12. I will have a look

**Comment by panos-lunarg** [comment] 2022-07-08 12:05
Ok figured out what's going on.

My impression is that Angle is enabled by default on Pixel 6 + Android 12, although I might be wrong as I haven't crossed check it. It doesn't really matter as the bottom line is that we end up with 2 simultaneous calls to `vkCreateInstance`. There are multiple mutexes involved down that codepath which are causing a deadlock. Basically this is what roughly is going on:

thread 1: vkCreateInstance -> `lock_shared()`
thread 1: CreateInstance -> lock instance mutex
thread 2: vkCreateInstance -> `lock_shared()`
thread 2: CreateInstance -> lock instance mutex <- blocks
thread 1: `lock()` <- Deadlock and also illegal/undefined behavior

Basically there are two problems here.
1. Thread 1 calling `lock()` is undefined behavior. [If lock is called by a thread that already owns the mutex in any mode (shared or exclusive), the behavior is undefined.](https://en.cppreference.com/w/cpp/thread/shared_timed_mutex/lock) So thread 1 needs to `unlock_shared()` first. But even if it did it would still be doomed to end up in a deadlock because thread 2 is holding a `shared_lock()` which also needs to `unlock_shared()` first.

2. There is a singleton logic going on which introduces a new mutex (instance mutex). So thread 2, even if it was programmed to `unlock_shared()`, doesn't get a chance to do so as it is blocked on that new mutex.

Working on a solution...

**Comment by panos-lunarg** [comment] 2022-07-21 06:28
Fixed by #735

**Closed by panos-lunarg** 2022-07-21 06:28 UTC
Labels: bug, P1, capture
