### ISSUE TITLE
Regression in shader replace (hash instead of handle)

### ISSUE THREAD

**Issue by dorian-apanel-intel** [LunarG/gfxreconstruct#668] opened 2022-03-16 14:25 UTC
Both extract and replace-shaders command line help states that after extraction, I can just use the same folder for replace shaders and shaders are in format sh{handle}.

Extraction works as expected, but replacing not.
In process monitor I see that replay tries to access totally different files like sh2623864620 instead of sh9.

I see using handle was implemented here 9e1a0316bc54926cafc33bd872e2e6aabcd441ab, but it somehow was partially reverted here 84fb52ddded424ebf68d7c7c84d708da9827e371

It still looks for hashes.

**Comment by bradgrantham-lunarg** [comment] 2022-03-21 18:31
Looks like a simple enough mistake; I've posted a PR that I think restores the intended behavior.  With the PR, I see messages like:
```
[gfxrecon] INFO - Replacement shader found: gfxrecon_capture_frames_100_through_300_20220215T102624.gfxr.shaders\sh37
[gfxrecon] INFO - Replacement shader found: gfxrecon_capture_frames_100_through_300_20220215T102624.gfxr.shaders\sh38
```
Which is what I expect.

Are you able to try out the branch in the PR?

**Comment by bradgrantham-lunarg** [comment] 2022-03-21 19:10
Fixed by #673, but see also #675

**Closed by bradgrantham-lunarg** 2022-03-21 19:10 UTC

**Comment by dorian-apanel-intel** [comment] 2022-03-22 07:04
Hi,
Checked top of dev branch just now and it works as expected.

***@***.***

This override added 0.5 of red component to fragment shader.

Thank you for this fix,
Dorian Apanel

**Comment by dorian-apanel-intel** [comment] 2022-03-22 07:06
Checked top of dev branch just now (b47e1add213fb4a3478b12c97bc535614ef7c5c3) and it works as expected.


This override added 0.5 of red component to fragment shader.

![image](https://user-images.githubusercontent.com/72810961/159426230-4e3eb6e3-7fd3-41f1-a8dd-c4309bb41782.png)

Thank you :)
