### ISSUE TITLE
Multiple resources sharing the same GPUVA range

### ISSUE THREAD

**Issue by rurra-amd** [LunarG/gfxreconstruct#1064] opened 2023-03-24 13:55 UTC
Sometimes multiple resources share the same GPUVA range.

If given a certain GPUVA to obtain a resource, GFXR will only return the first resource assigned to that GPUVA However, this resource might not the one we are looking for.

**Comment by davidd-lunarg** [comment] 2023-03-28 23:26
Duplicate of #1003

**Closed by davidd-lunarg** 2023-03-28 23:26 UTC
