### ISSUE TITLE
Using fread to populate memory returned by vkMapMemory fails when traced using pageguard

### ISSUE THREAD

**Issue by per-mathisen-arm** [LunarG/gfxreconstruct#686] opened 2022-04-20 12:34 UTC
This is a rather curious corner case. If tracing with pageguard, then doing fread to populate memory returned from vkMapMemory will fail. The same code when not traced will work fine. Using memcpy or other means of copying memory works fine. Using assisted memory tracking mode works fine.

Example:

> void* pBuf = NULL;
> vkMapMemory(..., &pBuf);
> fread(pBuf, size, 1, file); // <--- Returns != 1, errno = EFAULT

I made a small unit test to reproduce this issue in [https://github.com/ARM-software/tracetooltests ](https://github.com/ARM-software/tracetooltests) - see src/vulkan_copying_3.cpp. Run it with the -c 2 option to reproduce this behaviour. You can see with the -c 0 and -c 1 options that neither memcpy and memset have this problem. Also reproduced with our own vktrace-based tracer.

**Comment by werman** [comment] 2022-05-07 13:56
`fread` may lead to the kernel writing into the buffer (if `fread` doesn't buffer the read), `memcpy`/`memset` happens entirely in the userspace.

So what happens when kernel tries to write into write-protected memory? Kernel won't explode, but the page fault we expect won't be thrown, and protected memory won't be written into. So the behavior you see is not a bug but unfortunately a limitation of this tracking method.

As a side note, I myself didn't even know about such possibility when implemented memory tracking for apitrace, but coincidentally recently I was asked what would happen in such case =)

**Comment by panos-lunarg** [comment] 2022-06-28 12:49
I think @werman  is correct. In case `fread` is used `SIGSEGV` is not generated and `fread` simple fails with a `Bad address` error.

Initially I thought creating an internal implementation of `fread` in a separate `.so` file which would use an internal buffer. Redirecting calls to `fread` is not as simple as `dlopen`ing the file though. This is because existing calls to `fread` are resolved by the dynamic linker when the executable is being loaded and not when the `dlopen` will take place (much later). I.e. the `dlopen` is not going to change existing resolved symbols.

The only solution I can think of is the use of `LD_PRELOAD` but this is too intrusive as it needs to change the way the executable is invoked.

If anyone can think of a better alternative I would be delighted to hear it.

**Comment by panos-lunarg** [comment] 2022-07-11 06:52
Concluded that there is no viable solution for this problem and decided to live with it.
A note has been added in the documentation to warn users (#732)

**Closed by panos-lunarg** 2022-07-11 06:52 UTC
Labels: bug, P1, capture
