### ISSUE TITLE
GFXreconstruct cant replay the trace (specified extension does not exist)

### ISSUE THREAD

**Issue by NTMan** [LunarG/gfxreconstruct#327] opened 2020-02-13 22:09 UTC
GFXreconstruct cant replay the trace instead I see an error message that the specified extension does not exist.
But I made the trace on the same machine on which I try replay trace.
Gfxreconstruct I builded from the master branch.
```
$ ./packaging-work/git/gfxreconstruct/build/tools/replay/gfxrecon-replay gfxrecon_capture_20200214T023654.gfxr 
[gfxrecon] FATAL - API call vkCreateDevice returned error value VK_ERROR_EXTENSION_NOT_PRESENT that does not match the result from the capture file: VK_SUCCESS.  Replay cannot continue.
Replay has encountered a fatal error and cannot continue: the specified extension does not exist
```

[Example trace ](https://gitlab.freedesktop.org/mesa/mesa/uploads/72bfea8c9d30eeb8c5ff278021439799/gfxrecon_capture_20200214T023654.gfxr)

**Comment by dustin-lunarg** [comment] 2020-02-14 01:35
Are you trying to replay with a mesa build that is different than the build used for capture?

I see two extensions in the capture file that could be causing the problem:
- **VK_EXT_shader_demote_to_helper_invocation** - It looks like this was added to Mesa 19.3.0 for RADV/ACO only.
- **VK_AMD_shader_fragment_mask** - It looks like this may have been added last month.

So, it is possible that replay will fail when not using ACO or when using a mesa version that is more than a month old.

Attempting to replay the example file on my system, AMD RADV VEGA10 (LLVM 9.0.0), produced the same error, but I was able to work around the error by modifying the replay tool to strip out the two extensions that I listed above.  Replay worked when those two extensions were removed.

This is the diff for the change that I made to remove the extensions, if you want to try it: [filter_extensions.diff](https://gist.github.com/dustin-lunarg/27463642aec1d150c4f4ffd0338d8518)

That is a one-off fix that is specific to this case, but we could create a generic fix by adding a replay option that would remove unsupported extensions from instance and device creation, which could address cases like this where an extension was enabled but may not be required.

**Comment by NTMan** [comment] 2020-02-14 04:22
> Are you trying to replay with a mesa build that is different than the build used for capture?

No, both Mesa builds is same.

> So, it is possible that replay will fail when not using ACO

Oh, my fault. I forgot to enable ACO for replaying trace, thanks.

> This is the diff for the change that I made to remove the extensions, if you want to try it: filter_extensions.diff

Thanks again, it works.
But I made capture in 4K resolution and replaying looks like in Full HD (picture did not fit in the screen)

![Screenshot from 2020-02-14 09-17-45](https://user-images.githubusercontent.com/200750/74501287-7be41080-4f0b-11ea-804f-d9c6f81aebbd.png)

**Comment by dustin-lunarg** [comment] 2020-02-14 18:46
Does the replay tool print any warning messages about screen size? When I play the file on my 2560x1440 monitor, the result matches the screenshot that you provided and I get an error message that says:
>[gfxrecon] WARNING - Requested window size (3840x2160) exceeds current screen size (2560x1440); replay may fail due to inability to create a window of the appropriate size.

If I connect a 4K monitor, the replay enters full screen mode and has the correct size.  I see the same behavior with both the dev and master branches.

Replay will determine window size from the swapchain size, and will only try to enter fullscreen mode when the window/swapchain size matches the monitor size.  We could add an option to always force fullscreen or force a specific window size, if you think that would help.

**Comment by NTMan** [comment] 2020-02-14 18:53
I didn't see messages that window size (3840x2160) exceeds the current screen size.
But I use scaling in DE 200%. And I guess replaying uses this scaling by mistake.

![Screenshot from 2020-02-14 23-50-06](https://user-images.githubusercontent.com/200750/74558817-d2416580-4f84-11ea-9113-e0066a0874dc.png)

**Comment by dustin-lunarg** [comment] 2020-02-14 19:53
I wasn't able to reproduce this from Gnome with 200% scaling or KDE with 2x scaling on a Fedora 31 system.  The replay was the correct size for both cases.  If you would like us to look into this, could you provide details for the Linux distribution that you are using so that we can try to reproduce your environment for testing?

**Comment by dustin-lunarg** [comment] 2020-02-14 21:38
Never mind, I was able to reproduce the issue on GNOME when replaying with a Wayland surface.  My previous tests were with Xcb surfaces.

One difference between master and dev is that dev now depends on xcb-keysyms.  If you did not intentionally build the replay tool with Wayland support, it is possible that you got a Wayland build because xcb-keysyms was missing (libxcb-keysyms1-dev for Ubuntu / xcb-util-keysysms-devel for Fedora).

**Comment by NTMan** [comment] 2020-02-16 20:50
> Never mind, I was able to reproduce the issue on GNOME when replaying with a Wayland surface. My previous tests were with Xcb surfaces.

Yes, I using Wayland session. And under Wayland replay working only in window with Gnome scaling.

Under Gnome X Session replay didn't worked on my side:

```
$ RADV_PERFTEST=aco ~/packaging-work/git/gfxreconstruct/build/tools/replay/gfxrecon-replay gfxrecon_capture_20200214T023654.gfxr 
[gfxrecon] ERROR - Failed to connect to the Wayland display server
Failed to initialize platform specific window system management.
Ensure that the appropriate Vulkan platform extensions have been enabled.
```

> One difference between master and dev is that dev now depends on xcb-keysyms. If you did not intentionally build the replay tool with Wayland support, it is possible that you got a Wayland build because xcb-keysyms was missing (libxcb-keysyms1-dev for Ubuntu / xcb-util-keysysms-devel for Fedora).

Yep, I installed `xcb-util-keysyms-devel` for success building.

I see you know about Fedora packaging, but for the successful build I had to make edits cmake files because the paths on Fedora are different from your.

![Screenshot from 2020-02-17 01-42-43](https://user-images.githubusercontent.com/200750/74612444-4f0c4500-5127-11ea-847f-97e500d50b2e.png)
![Screenshot from 2020-02-17 01-42-38](https://user-images.githubusercontent.com/200750/74612448-55022600-5127-11ea-9c37-fca95a702368.png)

**Comment by dustin-lunarg** [comment] 2020-05-22 17:24
The latest release contains improvements to Wayland support, which should resolve the scaling issue that was described above.  I'm going to close this as I believe that both the initial issue and the scaling issue should be resolved, but feel free to create a new issue if you continue to have problems with scaling.

**Closed by dustin-lunarg** 2020-05-22 17:24 UTC
